openapi: 3.1.0
info:
  title: Translation api
  version: "1.0"

servers:
  - url: http://localhost:1080/
tags:
  - name: Translation
paths:
  /translations:
    get:
      tags:
        - Translation
      summary: Retrieve a translation.
      parameters:
        - name: lang
          in: query
          required: true
          schema:
            type: string
            examples:
              - "fr"
              - "en"
        - name: key
          in: query
          required: true
          schema:
            type: string
            examples:
              - "SHIRT"
              - "BLUE"
              - "COLOR"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TranslationEntry"
        "404":
          description: Translation not found

components:
  schemas:
    TranslationEntry:
      type: object
      required:
        - key
        - lang
        - label
      properties:
        key:
          type: string
          description: "The unique identifier for the translation"
          examples:
            - "RED"
        lang:
          type: string
          description: "The ISO language code"
          examples:
            - "fr"
        label:
          type: string
          description: "The translated text value"
          examples:
            - "rouge"
